development:
  backend:
    ip: ''
    port: ''
    debug_mode: true
    db_ip: 'localhost' # The address of the database server.
  frontend:
    ip: ''
    port: ''
  logging:
    level: 'DEBUG'
    format: '[%(asctime)s | %(levelname)s | %(name)s]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
deployment: ''
